import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  // The CSS variable name we want to use for this font
  variable: "--font-geist-sans",
  // Subsets - fonts often come included with multiple character sets (latin, cyrillic etc.)
  // By specyfying subsets, Next.js only loads the characters you need, reducing the bundle size and improving performance.
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// [Metadata]
// This is helpful for SEO and sharing (like when your page appears on Google or social media)
export const metadata: Metadata = {
  title: "Create Next App", // This becomes the <title> in the browser tab
  description: "Generated by create next app", // This becomes the <meta name="description"...>
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
